import type { Metadata } from "next";
import { Geist_Mono } from "next/font/google";
import { SnackbarProvider } from "seed-design/ui/snackbar";
import "./globals.css";
import { Providers } from "./providers";

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const seedColorSchemeScript = `
try {
  var prefersDark = window.matchMedia("(prefers-color-scheme: dark)");
  var apply = function () {
    document.documentElement.dataset.seedUserColorScheme = prefersDark.matches ? "dark" : "light";
  };
  if ("addEventListener" in prefersDark) {
    prefersDark.addEventListener("change", apply);
  } else if ("addListener" in prefersDark) {
    prefersDark.addListener(apply);
  }
  apply();
} catch (e) {}
`;

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      data-seed
      data-seed-color-mode="system"
      data-seed-user-color-scheme="light"
      suppressHydrationWarning
      className={`${geistMono.variable} h-full antialiased`}
    >
      <head>
        <meta name="color-scheme" content="light dark" />
        <script
          // biome-ignore lint/security/noDangerouslySetInnerHtml: seed-design system color-scheme sync must run before hydration
          dangerouslySetInnerHTML={{ __html: seedColorSchemeScript }}
        />
      </head>
      <body className="min-h-full flex flex-col">
        <Providers>
          <SnackbarProvider>{children}</SnackbarProvider>
        </Providers>
      </body>
    </html>
  );
}
